name: Fortify on Demand Scan
on:
  workflow_dispatch:           # <— enables the “Run workflow” butto
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  FoD-SAST-Scan:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out source code
        uses: actions/checkout@v4  
      - name: Setup Java
        uses: actions/setup-java@v4   # Set up build tool(s) required to build your project
        with:
          distribution: 'temurin' # See  'Supported distributions' for available options
          java-version: '25'
    # permissions:               # When overriding default permissions, following are required:
    #   contents: read           # Required for checkout action
    #   security-events: write   # Required for  publishing security reports to GitHub Security tab
    #   pull-requests: write     # Required if DO_PR_COMMENT is set to true
      - uses: actions/checkout@v4            # Check out source code
        name: Run FoD SAST Scan
      - uses: fortify/github-action@v3       # Run Fortify scans
        with:
          debug: true
        env:
          #FOD_URL: ${{ vars.FOD_URL }}
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_CLIENT_ID: ${{ secrets.FOD_CLIENT_ID }}
          FOD_CLIENT_SECRET: ${{ secrets.FOD_CLIENT_SECRET }}
          FOD_RELEASE: ${{secrets.FOD_RELEASE_ID}}
          EXTRA_PACKAGE_OPTS: -bt none 
          DO_WAIT: true
          # FOD_RELEASE: MyApp:main        # Optional: defaults to repo:branch
          FCLI_BOOTSTRAP_VERSION: v3.15  # Optional if you prefer stability over latest
          DO_EXPORT: true
          DO_PACKAGE_DEBUG: true
          # RUNNER_DEBUG: '1'  # Enable GitHub Actions debug logging
          # ACTIONS_STEP_DEBUG: 'true'  # More verbose step output
          # FCLI_LOG_LEVEL: DEBUG  # Enable FCLI debug logging
          # FCLI_LOG_FILE: fcli.log  # Save logs to file


          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
